# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unraidcli < Formula
  desc "Command-line interface for managing Unraid servers"
  homepage "https://github.com/01dnot/unraidcli"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/01dnot/unraidcli/releases/download/v0.1.0/unraidcli-darwin-amd64"
      sha256 "ffbda090f316a0e5292f1141fc3f563e3b75dac3178c00a31663789e5fed0cb1"

      def install
        bin.install "unraidcli"
      end
    end
    on_arm do
      url "https://github.com/01dnot/unraidcli/releases/download/v0.1.0/unraidcli-darwin-arm64"
      sha256 "a9344b960cc708226f8afaad1558975b30294646e1c4b27605af6546eb8e69f6"

      def install
        bin.install "unraidcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/01dnot/unraidcli/releases/download/v0.1.0/unraidcli-linux-amd64"
        sha256 "08eb81d9d6b344eb91d64cb484ce84d32a3d5857aeb98b492bcb129605a30b3d"

        def install
          bin.install "unraidcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/01dnot/unraidcli/releases/download/v0.1.0/unraidcli-linux-arm64"
        sha256 "bc6411f296533ad52c93efd89eea7b6562233c10b4f7ede0235724b6370a813e"

        def install
          bin.install "unraidcli"
        end
      end
    end
  end

  test do
    system "#{bin}/unraidcli", "--version"
  end
end
